<?xml version="1.0"?>

<robot name="iris" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass0" value="0.001" /> <!-- mass link 0 -->
  <xacro:property name="mass1" value="0.01" /> <!-- mass link 1 -->
  <xacro:property name="mass2" value="0.163" /> <!-- mass link 2 -->
  <xacro:property name="mass3" value="0.093" /> <!-- mass link 3 -->
  <xacro:property name="mass4" value="0.102" /> <!-- mass link 4 -->
<!--   <xacro:property name="masss" value="0.02" /> mass pinza lato sinistro - ferma -->
  <xacro:property name="massd" value="0.0135" /> <!-- mass pinza lato destro - mobile , valori foto*2.7-->
  <xacro:property name="width" value="0.026" /> <!-- 026 Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height0" value="0.5" /> <!-- 0.005  Link 0 -->
  <xacro:property name="height1" value="0.05" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.19585" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.063" /> <!-- Link 3, la parte 1 -->
  <xacro:property name="height32" value="0.021" /> <!-- Link 3, la parte 2 -->
  <xacro:property name="height4" value="0.067" /> <!-- Link 4 -->
  <xacro:property name="heights" value="0.048" /> <!-- Link pinza lato sinistro -->
  <xacro:property name="heightd" value="0.048" /> <!-- Link pinza lato destro -->
  <xacro:property name="heights2" value="0.048" /> <!-- Link pinza lato sinistro parte curva -->
  <xacro:property name="heightd2" value="0.048" /> <!-- 0.066 - Link pinza lato destro parte curva -->
  <xacro:property name="spessorepinza" value="0.004" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="axel_offset" value="0.005" /> <!-- Space btw top of beam and the each joint -->

  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
  <!-- Instantiate iris "mechanics" -->
  <xacro:include filename="$(find rotors_description)/urdf/iris.xacro" />

  <!-- connetti il braccio
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot.xacro" />
 -->

  <link name="link0">
    <collision>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height0}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height0}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <mass value="${mass0}"/>
      <inertia
	  ixx="${mass0 / 12.0 * (width*width + height0*height0)}" ixy="0.0" ixz="0.0"
	  iyy="${mass0 / 12.0 * (height0*height0 + width*width)}" iyz="0.0"
	  izz="${mass0 / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint0" type="fixed">
    <parent link="base_link"/>
    <child link="link0"/>
    <origin xyz="0 0 0" rpy="${PI} 0 0"/>
    <dynamics damping="0"/>
  </joint>

  <!-- Instantiate a controller. -->
  <xacro:controller_plugin_macro
    namespace="${namespace}"
    imu_sub_topic="imu"
    >
  </xacro:controller_plugin_macro>

  <xacro:if value="$(arg enable_mavlink_interface)">
  <!-- Instantiate mavlink telemetry interface. -->
  <xacro:mavlink_interface_macro
    namespace="${namespace}"
    imu_sub_topic="imu"
    >
  </xacro:mavlink_interface_macro>
  </xacro:if>

  <!-- Mount an ADIS16448 IMU. -->
  <xacro:imu_plugin_macro
    namespace="${namespace}"
    imu_suffix=""
    parent_link="base_link"
    imu_topic="imu"
    mass_imu_sensor="0.015"
    gyroscope_noise_density="0.0003394"
    gyroscopoe_random_walk="0.000038785"
    gyroscope_bias_correlation_time="1000.0"
    gyroscope_turn_on_bias_sigma="0.0087"
    accelerometer_noise_density="0.004"
    accelerometer_random_walk="0.006"
    accelerometer_bias_correlation_time="300.0"
    accelerometer_turn_on_bias_sigma="0.1960"
  >
    <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:imu_plugin_macro>

  <xacro:if value="$(arg enable_ground_truth)">
    <!-- Mount an IMU providing ground truth. -->
    <xacro:imu_plugin_macro
      namespace="${namespace}"
      imu_suffix="gt"
      parent_link="base_link"
      imu_topic="ground_truth/imu"
      mass_imu_sensor="0.00001"
      gyroscope_noise_density="0.0"
      gyroscopoe_random_walk="0.0"
      gyroscope_bias_correlation_time="1000.0"
      gyroscope_turn_on_bias_sigma="0.0"
      accelerometer_noise_density="0.0"
      accelerometer_random_walk="0.0"
      accelerometer_bias_correlation_time="300.0"
      accelerometer_turn_on_bias_sigma="0.0"
    >
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:imu_plugin_macro>

    <!-- Mount a generic odometry sensor providing ground truth. -->
    <xacro:odometry_plugin_macro
      namespace="${namespace}/ground_truth"
      odometry_sensor_suffix="gt"
      parent_link="base_link"
      pose_topic="pose"
      pose_with_covariance_topic="pose_with_covariance"
      position_topic="position"
      transform_topic="transform"
      odometry_topic="odometry"
      parent_frame_id="world"
      mass_odometry_sensor="0.00001"
      measurement_divisor="1"
      measurement_delay="0"
      unknown_delay="0.0"
      noise_normal_position="0 0 0"
      noise_normal_quaternion="0 0 0"
      noise_normal_linear_velocity="0 0 0"
      noise_normal_angular_velocity="0 0 0"
      noise_uniform_position="0 0 0"
      noise_uniform_quaternion="0 0 0"
      noise_uniform_linear_velocity="0 0 0"
      noise_uniform_angular_velocity="0 0 0"
      enable_odometry_map="false"
      odometry_map=""
      image_scale=""
    >
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </xacro:odometry_plugin_macro>
  </xacro:if>

  <xacro:if value="$(arg enable_logging)">
    <!-- Instantiate a logger -->
    <xacro:bag_plugin_macro
      namespace="${namespace}"
      bag_file="$(arg log_file)"
      rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}"
    >
    </xacro:bag_plugin_macro>
  </xacro:if>

</robot>

